# Generated by Django 5.1.2 on 2024-11-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='healthy_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='healthy_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_ka',
        ),
    ]
