services:
  db:
    container_name: store_hub_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-q", "-d", "blog", "-U", "blog" ]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
  postgres_data:

